### ISSUE TITLE
timeout

### ISSUE THREAD

**Issue by flaviosuardi** [giuseppebrb/AldoGiovanniGiacomoSlackApp#1]
Le chiamate vanno in `timeout` 😢 

Qualsiasi cosa scriva in Slack (es: `/aldogiovannigiacomo random dialogue`) mi ritorna: `/aldogiovannigiacomo failed with the error "operation_timeout"`

**Comment by giuseppebrb** [comment]
Azure sa essere abbastanza antipatico :confused:. Dovrei aver risolto i problemi di deploy che c'erano! Prova a vedere se la risposta arriva, altrimenti disinstalla e reinstalla l'estensione :smile:! 

N.B. La response ci può mettere fino ad un secondo e mezzo per arrivare, anche in questo caso il free-tier di azure non aiuta!
